version: "2"
run:
  concurrency: 4
  tests: false
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - lll
    - mnd
    - nlreturn
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - wsl_v5
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
