run:
  timeout: 10m
  concurrency: 4
  tests: false

issues:
  exclude-dirs-use-default: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - unconvert
    - staticcheck
    - ineffassign
    - unparam
    - forbidigo
    - gomodguard
    - gosimple
    - gosec
    - gocritic
    - lll
    - whitespace
    - errcheck
    - wsl
    - exhaustive
    - gocyclo
    - mnd
    - errorlint
    - nlreturn
    - forcetypeassert
    - godox
    - godot
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      shadow:
        strict: true

  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
