linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - unconvert
    - staticcheck
    - ineffassign
    - unparam
    - forbidigo
    - gomodguard
    - gosimple
    - gosec

run:
  timeout: 10m
  concurrency: 4
  skip-dirs-use-default: false
